FROM openjdk:8-jdk-alpine

RUN apk update && \
apk add curl busybox tzdata && \
apk --no-cache add ttf-dejavu fontconfig && \
cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
echo Asia/Shanghai > /etc/timezone && \
apk del tzdata && \
rm -rf /tmp/ /var/cache/apk/
# copy arthas
COPY --from=hengyunabc/arthas:latest /opt/arthas /opt/arthas
